name = "re-terminal"
license = "MIT"
licenselink = "https://github.com/mirus-ua/hugo-theme-re-terminal/blob/master/LICENSE.md"
description = "A simple, retro theme for Hugo."
homepage = "https://github.com/mirus-ua/hugo-theme-re-terminal/"
tags = [
  "blog",
  "clean",
  "customizable",
  "dark",
  "highlighting",
  "minimal",
  "monotone",
  "multilingual",
  "personal",
  "responsive",
  "simple",
  "technical",
  "retro",
]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.129

[author]
name = "Mirus"
homepage = "https://nebrowser.com"
